- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:   #ansible.builtin.packages will work for all distributions
      name: nginx
      state: latest

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes