- name: variables
  hosts: localhost
  become: yes
  vars:
   name: "shabeena"
   course: "devops"
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "hi i am {{name}} ,im learning {{course}}"