- hosts: localhost
  name: variables
  become: yes
  vars:
  #play level variable
   name: "shabeena"
   course: "devops"
  tasks:
  - name: print information
    vars:
    #task level variable
     course: "terraform"
    ansible.builtin.debug:
     msg: "hi i am {{name}} ,im learning {{course}}"

  - name: print information
    ansible.builtin.debug:
     msg: "hi i am{{name}}"