- name: default value
  hosts: localhost
  become: yes
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "hello {{course | default('ansible')}}"

- name: upper case
  hosts: localhost
  vars:
   greetings: "hello gudmorning"
  tasks:
  - name: convert into uppercase 
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"

- name: lower case
  hosts: localhost
  vars:
   greeting: "HELO GOOD Morning"
  tasks:
  - name: convert into lowercase 
    ansible.builtin.debug:
     msg: "{{greeting| lower}}"

- name: remover duplicates
  hosts: localhost
  vars:
   numbers: [1,2,3,3,4,5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
     msg: "{{numbers | unique}}"

- name: print min and max
  hosts: localhost
  vars:
   ages: [25,56,78,31]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
     msg: "min age: {{ages | min}},max age: {{ages | max}}"