- name: default value
  hosts: localhost
  become: yes
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "hello {{course | default('ansible')}}"

- name: upper case
  hosts: localhost
  vars:
   greetings: "hello gudmorning"
  tasks:
  - name: convert into uppercase 
    ansible.builtin.debug:
     msg: "{{greetings | upper}}"

- name: lower case
  hosts: localhost
  vars:
   greeting: "HELO GOOD Morning"
  tasks:
  - name: convert into lowercase 
    ansible.builtin.debug:
     msg: "{{greetings| lower}}"